# Analyses clips for stabilisation.
#
#   powershell -ExecutionPolicy Bypass -File edition/media/analyse-stabilisation.ps1
#
# Stabilisation is two passes: this one measures camera motion and writes
# the vectors beside the media; the render then applies them. Doing it here
# means the editor is not blocked while a clip is analysed, and the result
# is reused for every export.
#
# Existing analyses are skipped unless -Force is given.

[CmdletBinding()]
param(
    [string]$Name,
    [int]$Shakiness = 5,
    [int]$Accuracy = 15,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

$here = $PSScriptRoot
$bin = if ($env:EDITOGETHER_FFMPEG_BIN) { $env:EDITOGETHER_FFMPEG_BIN } else { "" }
$ffmpeg = if ($bin) { Join-Path $bin 'ffmpeg.exe' } else { (Get-Command ffmpeg).Source }

$indexPath = Join-Path $here 'index.json'
if (-not (Test-Path $indexPath)) { throw "no media index; run build-media-index.ps1 first" }
$index = Get-Content $indexPath -Raw | ConvertFrom-Json

$vectorDir = Join-Path $here 'stabilisation'
New-Item -ItemType Directory -Force $vectorDir | Out-Null

$analysed = 0
$skipped = 0

foreach ($item in $index.media) {
    if ($item.kind -ne 'video') { continue }
    if ($Name -and $item.name -ne $Name) { continue }

    $source = Join-Path $here (Split-Path -Leaf $item.source)
    if (-not (Test-Path $source)) {
        Write-Warning "missing source for $($item.name)"
        continue
    }

    $vectors = Join-Path $vectorDir "$($item.name).trf"
    if ((Test-Path $vectors) -and -not $Force) {
        Write-Host "  $($item.name): already analysed"
        $item | Add-Member -NotePropertyName stabilisation `
            -NotePropertyValue "media/stabilisation/$($item.name).trf" -Force
        $skipped++
        continue
    }

    Write-Host "  $($item.name): measuring camera motion"
    # vidstabdetect writes the vectors and discards the picture: nothing is
    # encoded on this pass.
    $escaped = ($vectors -replace '\\', '/') -replace ':', '\:'
    & $ffmpeg -y -loglevel error -i $source `
        -vf "vidstabdetect=shakiness=${Shakiness}:accuracy=${Accuracy}:result='${escaped}'" `
        -f null -
    if ($LASTEXITCODE -ne 0) { throw "analysis failed for $($item.name)" }

    $item | Add-Member -NotePropertyName stabilisation `
        -NotePropertyValue "media/stabilisation/$($item.name).trf" -Force
    $analysed++
}

# Record the analyses in the index, the way proxies are recorded.
$json = @{ media = $index.media } | ConvertTo-Json -Depth 8
Set-Content -Path $indexPath -Value $json -Encoding utf8

$body = $index.media | ConvertTo-Json -Depth 8
if ($index.media.Count -eq 1) { $body = "[$body]" }
$js = @"
// Generated by build-media-index.ps1 / build-proxies.ps1 /
// analyse-stabilisation.ps1 — do not edit by hand.
.pragma library

var media = $body
"@
Set-Content -Path (Join-Path $here 'index.js') -Value $js -Encoding utf8

Write-Host ""
Write-Host "analysed $analysed, skipped $skipped"
