# Builds the media index the shell reads: real metadata from ffprobe, real
# thumbnails from decoded frames, real peaks from decoded PCM.
#
#   powershell -ExecutionPolicy Bypass -File edition/media/build-media-index.ps1
#
# Requires ffmpeg and ffprobe on PATH (or set EDITOGETHER_FFMPEG_BIN).

$ErrorActionPreference = 'Stop'
$here = $PSScriptRoot
$bin = if ($env:EDITOGETHER_FFMPEG_BIN) { $env:EDITOGETHER_FFMPEG_BIN } else { "" }
$ffmpeg = if ($bin) { Join-Path $bin 'ffmpeg.exe' } else { (Get-Command ffmpeg).Source }
$ffprobe = if ($bin) { Join-Path $bin 'ffprobe.exe' } else { (Get-Command ffprobe).Source }

$thumbDir = Join-Path $here 'thumbs'
New-Item -ItemType Directory -Force $thumbDir | Out-Null

function Get-Duration($path) {
    $out = & $ffprobe -v error -show_entries format=duration -of csv=p=0 $path
    return [double]$out
}

function Get-Stream($path, $stream, $entries) {
    $out = & $ffprobe -v error -select_streams $stream -show_entries $entries -of csv=p=0 $path
    return ($out | Select-Object -First 1)
}

# Peaks: decode to mono 8-bit PCM and take the maximum excursion per bucket.
# This is the real signal, not an approximation of one.
function Get-Peaks($path, $buckets) {
    $raw = Join-Path $env:TEMP ("etpeaks-" + [IO.Path]::GetFileNameWithoutExtension($path) + ".raw")
    & $ffmpeg -y -loglevel error -i $path -ac 1 -ar 4000 -f u8 $raw
    $bytes = [IO.File]::ReadAllBytes($raw)
    Remove-Item $raw -ErrorAction SilentlyContinue
    if ($bytes.Length -eq 0) { return @() }
    $peaks = @()
    $size = [Math]::Max(1, [Math]::Floor($bytes.Length / $buckets))
    for ($b = 0; $b -lt $buckets; $b++) {
        $start = $b * $size
        if ($start -ge $bytes.Length) { break }
        $end = [Math]::Min($bytes.Length, $start + $size)
        $peak = 0.0
        for ($i = $start; $i -lt $end; $i++) {
            $v = [Math]::Abs($bytes[$i] - 128) / 128.0
            if ($v -gt $peak) { $peak = $v }
        }
        $peaks += [Math]::Round($peak, 3)
    }
    return $peaks
}

$entries = @()

foreach ($file in Get-ChildItem -Path (Join-Path $here '*') -Include *.mp4, *.wav -File) {
    $path = $file.FullName
    $name = [IO.Path]::GetFileNameWithoutExtension($file.Name)
    $duration = Get-Duration $path
    $hasVideo = (Get-Stream $path 'v:0' 'stream=codec_name')
    $entry = [ordered]@{
        label    = $file.Name
        name     = $name
        duration = [Math]::Round($duration, 2)
        kind     = if ($hasVideo) { 'video' } else { 'audio' }
        source   = 'media/' + $file.Name
    }

    if ($hasVideo) {
        $size = Get-Stream $path 'v:0' 'stream=width,height'
        $rate = Get-Stream $path 'v:0' 'stream=r_frame_rate'
        $entry.codec = $hasVideo
        $entry.size = $size -replace ',', ' x '
        $entry.rate = $rate
        # Six frames sampled evenly across the clip.
        $thumbs = @()
        for ($i = 0; $i -lt 6; $i++) {
            $t = $duration * ($i + 0.5) / 6
            $out = Join-Path $thumbDir "$name-$i.jpg"
            & $ffmpeg -y -loglevel error -ss $t -i $path -frames:v 1 -vf "scale=160:-1" -q:v 4 $out
            if (Test-Path $out) { $thumbs += "media/thumbs/$name-$i.jpg" }
        }
        $entry.thumbs = $thumbs
        $entry.peaks = @()
    } else {
        $entry.codec = (Get-Stream $path 'a:0' 'stream=codec_name')
        $entry.peaks = Get-Peaks $path 220
        $entry.thumbs = @()
    }

    $entries += [pscustomobject]$entry
    Write-Host "indexed $($file.Name): $($entry.kind), $($entry.duration)s"
}

$json = @{ media = $entries } | ConvertTo-Json -Depth 6
Set-Content -Path (Join-Path $here 'index.json') -Value $json -Encoding utf8

# QML blocks local XHR reads, so the shell imports this instead of fetching.
$body = $entries | ConvertTo-Json -Depth 6
if ($entries.Count -eq 1) { $body = "[$body]" }
$js = @"
// Generated by build-media-index.ps1 — do not edit by hand.
.pragma library

var media = $body
"@
Set-Content -Path (Join-Path $here 'index.js') -Value $js -Encoding utf8
Write-Host "wrote index.json and index.js with $($entries.Count) items"
