# Builds editing proxies for the media in this folder.
#
#   powershell -ExecutionPolicy Bypass -File edition/media/build-proxies.ps1
#
# A proxy is a small, cheap-to-decode copy used while cutting. Delivery
# always renders from the original, so proxies never affect the output —
# they only make editing responsive on large media.
#
# Proxies are written to media/proxies/ and recorded in the index, which the
# shell reads. Existing proxies are skipped unless -Force is given.

[CmdletBinding()]
param(
    [int]$Height = 540,
    [int]$Crf = 26,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

$here = $PSScriptRoot
$bin = if ($env:EDITOGETHER_FFMPEG_BIN) { $env:EDITOGETHER_FFMPEG_BIN } else { "" }
$ffmpeg = if ($bin) { Join-Path $bin 'ffmpeg.exe' } else { (Get-Command ffmpeg).Source }
$ffprobe = if ($bin) { Join-Path $bin 'ffprobe.exe' } else { (Get-Command ffprobe).Source }

$proxyDir = Join-Path $here 'proxies'
New-Item -ItemType Directory -Force $proxyDir | Out-Null

$indexPath = Join-Path $here 'index.json'
if (-not (Test-Path $indexPath)) {
    throw "no media index; run build-media-index.ps1 first"
}
$index = Get-Content $indexPath -Raw | ConvertFrom-Json

$built = 0
$skipped = 0

foreach ($item in $index.media) {
    if ($item.kind -ne 'video') { continue }

    $source = Join-Path $here (Split-Path -Leaf $item.source)
    if (-not (Test-Path $source)) {
        Write-Warning "missing source for $($item.name)"
        continue
    }

    $sourceHeight = [int](& $ffprobe -v error -select_streams v:0 `
        -show_entries stream=height -of csv=p=0 $source)

    # A proxy that is not smaller than its source is pointless.
    if ($sourceHeight -le $Height) {
        Write-Host "  $($item.name): already $($sourceHeight)p, no proxy needed"
        $item | Add-Member -NotePropertyName proxy -NotePropertyValue "" -Force
        continue
    }

    $proxyName = "$($item.name)-proxy.mp4"
    $proxyPath = Join-Path $proxyDir $proxyName

    if ((Test-Path $proxyPath) -and -not $Force) {
        Write-Host "  $($item.name): proxy exists"
        $item | Add-Member -NotePropertyName proxy -NotePropertyValue "media/proxies/$proxyName" -Force
        $skipped++
        continue
    }

    Write-Host "  $($item.name): $($sourceHeight)p -> $($Height)p"
    # All-intra so scrubbing does not have to walk a GOP, and a fixed height
    # so every proxy decodes at a predictable cost.
    & $ffmpeg -y -loglevel error -i $source `
        -vf "scale=-2:$Height" `
        -c:v libx264 -preset veryfast -crf $Crf -g 1 -pix_fmt yuv420p `
        -c:a aac -b:a 128k `
        $proxyPath
    if ($LASTEXITCODE -ne 0) { throw "failed to build a proxy for $($item.name)" }

    $item | Add-Member -NotePropertyName proxy -NotePropertyValue "media/proxies/$proxyName" -Force
    $built++
}

# Rewrite the index, and the JS the shell imports alongside it.
$json = @{ media = $index.media } | ConvertTo-Json -Depth 8
Set-Content -Path $indexPath -Value $json -Encoding utf8

$body = $index.media | ConvertTo-Json -Depth 8
if ($index.media.Count -eq 1) { $body = "[$body]" }
$js = @"
// Generated by build-media-index.ps1 / build-proxies.ps1 — do not edit by hand.
.pragma library

var media = $body
"@
Set-Content -Path (Join-Path $here 'index.js') -Value $js -Encoding utf8

$originalSize = 0
$proxySize = 0
foreach ($item in $index.media) {
    if ($item.kind -ne 'video') { continue }
    $src = Join-Path $here (Split-Path -Leaf $item.source)
    if (Test-Path $src) { $originalSize += (Get-Item $src).Length }
    if ($item.proxy) {
        $pp = Join-Path $here (Split-Path -Leaf $item.proxy)
        $pp = Join-Path $proxyDir (Split-Path -Leaf $item.proxy)
        if (Test-Path $pp) { $proxySize += (Get-Item $pp).Length }
    }
}

Write-Host ""
Write-Host "built $built, skipped $skipped"
if ($proxySize -gt 0) {
    Write-Host ("originals {0:N1} MB, proxies {1:N1} MB ({2:N0}% of the media)" -f `
        ($originalSize / 1MB), ($proxySize / 1MB), ($proxySize / $originalSize * 100))
}
