"""Regenerates src/edition.qrc from what the shell actually consists of.

    python scripts/build-edition-qrc.py

The resource was hand-kept and fell fourteen files behind as the shell
grew, which would have left the in-app preview failing to load. Generating
it from disk means adding a panel cannot silently break the bundle.
"""

import glob
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def entries(pattern, alias_root, base):
    out = []
    for path in sorted(glob.glob(os.path.join(REPO, pattern), recursive=True)):
        rel = os.path.relpath(path, os.path.join(REPO, base)).replace(os.sep, "/")
        src = os.path.relpath(path, os.path.join(REPO, "src")).replace(os.sep, "/")
        out.append('    <file alias="%s/%s">%s</file>' % (alias_root, rel, src))
    return out


def main():
    lines = [
        "<!--",
        "  Generated by scripts/build-edition-qrc.py — do not hand-edit.",
        "",
        "  Bundles the edition shell and the design system it imports, so the",
        "  application can open the interface from its own resources rather",
        "  than from a source tree that may not be installed.",
        "-->",
        "<RCC>",
        '  <qresource prefix="/editogether">',
    ]

    lines += entries(
        "src/qml/modules/EdiTogether/**/*.qml",
        "modules/EdiTogether",
        "src/qml/modules/EdiTogether",
    )
    lines += entries(
        "src/qml/modules/EdiTogether/**/qmldir",
        "modules/EdiTogether",
        "src/qml/modules/EdiTogether",
    )
    lines += entries("edition/*.qml", "edition", "edition")
    lines += entries("edition/*.js", "edition", "edition")
    lines += entries("edition/icons/*.svg", "edition/icons", "edition/icons")
    # MediaLibrary imports the generated index, and the panels show the
    # thumbnails it names. Without these the shell loads to an error.
    lines += entries("edition/media/index.js", "edition/media", "edition/media")
    lines += entries("edition/media/thumbs/*", "edition/media/thumbs", "edition/media/thumbs")

    lines += ["  </qresource>", "</RCC>", ""]

    target = os.path.join(REPO, "src", "edition.qrc")
    with open(target, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))

    print("bundled %d files" % sum(1 for line in lines if "<file" in line))


if __name__ == "__main__":
    main()
